web/router.ex
defmodule Books.Router do
  use Books.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :authorization do
    plug Books.Plugs.Authorization
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Books do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/", Books do
    pipe_through [:browser, :authorization]

    resources "/users", UserController
    resources "/books", BookController
    resources "/borrowings", BorrowingController, only: [:index, :create]
  end

  scope "/auth", Books do
    pipe_through :browser # Use the default browser stack

    get "/:provider", AuthController, :index
    get "/:provider/callback", AuthController, :login
    delete "/", AuthController, :logout
  end

  # Other scopes may use custom stacks.
  # scope "/api", Books do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Books.LayoutView do
  use Books.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Phoenix!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= render "navigation.html", conn: @conn %>
    <div class="container" role="main">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= @inner %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/navigation.html.eex
<nav>
  <div class="top-bar">
    <div class="top-bar-left">
      <ul class="menu">
        <li><%= link("Home", to: page_path(@conn, :index)) %></li>
        <li><%= link("Books", to: book_path(@conn, :index)) %></li>
        <li><%= link("Users", to: user_path(@conn, :index)) %></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li>
          <%= if current_user(@conn) do %>
            <%= current_user(@conn)["email"] %>
            <%= tag(:img, src: current_user(@conn)["picture"]) %>
            <%= link("Sign out", to: auth_path(@conn, :logout), method: :delete) %>
          <% else %>
            <%= link("Sign in", to: auth_path(@conn, :index, "google")) %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>