web/router.ex
defmodule Books.Router do
  use Books.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :authorization do
    plug Books.Plugs.Authorization
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Books do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/", Books do
    pipe_through [:browser, :authorization]

    resources "/users", UserController
    resources "/books", BookController
    resources "/borrowings", BorrowingController, only: [:index, :create]
  end

  scope "/auth", Books do
    pipe_through :browser # Use the default browser stack

    get "/:provider", AuthController, :index
    get "/:provider/callback", AuthController, :login
    delete "/", AuthController, :logout
  end

  # Other scopes may use custom stacks.
  # scope "/api", Books do
  #   pipe_through :api
  # end
end

lib/books/endpoint.ex
defmodule Books.Endpoint do
  use Phoenix.Endpoint, otp_app: :books

  socket "/socket", Books.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :books, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_books_key",
    signing_salt: "v5XEg4yO"

  plug Books.Router
end

lib/books/plugs/authorization.ex
defmodule Books.Plugs.Authorization do
  import Plug.Conn

  def init(default), do: default
  def call(conn, _default) do
    if get_session(conn, :current_user) do
      conn
    else
      conn
      |> Phoenix.Controller
          .redirect(to: Books.Router.Helpers.auth_path(conn, :index, "google"))
      |> halt
    end
  end
end

lib/books/repo.ex
defmodule Books.Repo do
  use Ecto.Repo, otp_app: :books
end

web/models/book.ex
defmodule Books.Book do
  use Books.Web, :model

  schema "books" do
    field :author, :string
    field :title, :string
    field :isbn, :string
    field :cover, :string
    field :description, :string

    has_many :borrowings, Books.Borrowing

    timestamps
  end

  @required_fields ~w(author title isbn)
  @optional_fields ~w(cover description)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/controllers/book_controller.ex
defmodule Books.BookController do
  use Books.Web, :controller

  alias Books.Book

  plug :scrub_params, "book" when action in [:create, :update]

  def index(conn, _params) do
    books = Repo.all(Book)
    render(conn, "index.html", books: books)
  end

  def new(conn, _params) do
    changeset = Book.changeset(%Book{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"book" => book_params}) do
    changeset = Book.changeset(%Book{}, book_params)

    case Repo.insert(changeset) do
      {:ok, _book} ->
        conn
        |> put_flash(:info, "Book created successfully.")
        |> redirect(to: book_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    book = Repo.get!(Book, id)
    render(conn, "show.html", book: book)
  end

  def edit(conn, %{"id" => id}) do
    book = Repo.get!(Book, id)
    changeset = Book.changeset(book)
    render(conn, "edit.html", book: book, changeset: changeset)
  end

  def update(conn, %{"id" => id, "book" => book_params}) do
    book = Repo.get!(Book, id)
    changeset = Book.changeset(book, book_params)

    case Repo.update(changeset) do
      {:ok, book} ->
        conn
        |> put_flash(:info, "Book updated successfully.")
        |> redirect(to: book_path(conn, :show, book))
      {:error, changeset} ->
        render(conn, "edit.html", book: book, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    book = Repo.get!(Book, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(book)

    conn
    |> put_flash(:info, "Book deleted successfully.")
    |> redirect(to: book_path(conn, :index))
  end
end

web/views/book_view.ex
defmodule Books.BookView do
  use Books.Web, :view
end

web/templates/book/edit.html.eex
<h2>Edit book</h2>

<%= render "form.html", changeset: @changeset,
                        action: book_path(@conn, :update, @book) %>

<%= link "Back", to: book_path(@conn, :index) %>

web/templates/book/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :author, "Author", class: "control-label" %>
    <%= text_input f, :author, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :title, "Title", class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :isbn, "Isbn", class: "control-label" %>
    <%= text_input f, :isbn, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :cover, "Cover", class: "control-label" %>
    <%= text_input f, :cover, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :description, "Description", class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/book/index.html.eex
<h2>Listing books</h2>

<table class="table">
  <thead>
    <tr>
      <th>Author</th>
      <th>Title</th>
      <th>Isbn</th>
      <th>Cover</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for book <- @books do %>
    <tr>
      <td><%= book.author %></td>
      <td><%= book.title %></td>
      <td><%= book.isbn %></td>
      <td><%= book.cover %></td>
      <td><%= book.description %></td>

      <td class="text-right">
        <%= link "Show", to: book_path(@conn, :show, book), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: book_path(@conn, :edit, book), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: book_path(@conn, :delete, book), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New book", to: book_path(@conn, :new) %>

web/templates/book/new.html.eex
<h2>New book</h2>

<%= render "form.html", changeset: @changeset,
                        action: book_path(@conn, :create) %>

<%= link "Back", to: book_path(@conn, :index) %>

web/templates/book/show.html.eex
<h2>Show book</h2>

<ul>

  <li>
    <strong>Author:</strong>
    <%= @book.author %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @book.title %>
  </li>

  <li>
    <strong>Isbn:</strong>
    <%= @book.isbn %>
  </li>

  <li>
    <strong>Cover:</strong>
    <%= @book.cover %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @book.description %>
  </li>

</ul>

<%= link "Edit", to: book_path(@conn, :edit, @book) %>
<%= link "Back", to: book_path(@conn, :index) %>

<%= form_tag(borrowing_path(@conn, :create), method: :post) do %>
  <input type='hidden' name='borrowing[book_id]' value="<%= @book.id %>">
  <input type='submit' value='Borrow'>
<% end %>